Repository MusinsaWagon/front_v1, pull requests merged in 2025-01, with the labels that each got.

#30 feat : 이미지 경로 수정 및 디자인 조정
  package-lock.json
  package.json
  public/images/bell.png
  public/images/step1-1.png
  public/images/step1-2.png
  public/images/step1.png
  public/images/step2.png
  public/images/step3.png
  public/images/upload.png
  src/apis/enrollNotification.ts
  src/components/common/Header.tsx
  src/components/common/PriceCard.tsx
  src/components/common/ProductCard.tsx
  src/components/common/UserInput.tsx
  src/components/productDetail/DetailBody.tsx
  src/components/productDetail/EnrollModal.tsx
  src/components/productDetail/PriceInfo.tsx
  src/constant/priceCardsData.ts
  src/firebase.ts
  src/hooks/modal/getModalInfo.ts
  src/hooks/useMutation.ts
  src/pages/product/ProductDetail.tsx
  src/styles/.gitkeep
  src/styles/common/UserInput.styled.ts
  src/styles/modal/Modal.styled.ts
Labels: enhancement

#32 feat : 알림등록 성공 후 모달 렌더링
  src/components/common/Modal.tsx
  src/components/productDetail/EnrollModal.tsx
  src/components/signUp/FormWrapper.tsx
  src/hooks/signUp/useSignUp.ts
Labels: enhancement

#36 feat: 카테고리 drawer 통신 & axiosInstance public/private 통신 수정
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/apis/drawer/axios.ts
  src/apis/goodsData/axios.ts
  src/apis/login/axios.ts
  src/components/mainPage/Inquiry.tsx
  src/components/mainPage/SearchBox.tsx
  src/components/mainPage/categorys/BottomCategory.tsx
  src/components/mainPage/categorys/CategoryDrawer.tsx
  src/components/mainPage/categorys/TopCategory.tsx
  src/components/mainPage/products/ProductSection.tsx
  src/components/mainPage/types/categories.d.ts
  src/constant/theme.ts
  src/pages/Main.tsx
Labels: enhancement

#38 feat : 좋아요 기능 추가
  src/apis/productDetail/getProductDetail.ts
  src/components/productDetail/DetailBody.tsx
  src/components/productDetail/ProductImage.tsx
  src/firebase.ts
  src/hooks/useMutation.ts
  src/pages/product/ProductDetail.tsx
Labels: enhancement

#45 feat : 유효성 검사 및 vercel.json 설정 추가
  src/components/enrollProd/BodySection.tsx
  src/vercel.json
Labels: enhancement

#48 메인 페이지 전체 상품 하위 카테고리 리스트 fetch 및 redux로 상태 관리 변경 & 하위 카테고리 drawer 추가
  src/apis/ category/axios.ts
  src/apis/goodsData/axios.ts
  src/components/mainPage/Category.tsx
  src/components/mainPage/EntireProductList.tsx
  src/components/mainPage/ProductPreviewList.tsx
  src/components/mainPage/categorys/BottomCategory.tsx
  src/components/mainPage/categorys/CategoryDrawer.tsx
  src/components/mainPage/categorys/subCategoryDrawer/CategoryList.tsx
  src/components/mainPage/categorys/subCategoryDrawer/ListTitle.tsx
  src/components/mainPage/categorys/subCategoryDrawer/SubCategoryDrawer.tsx
  src/components/search/SearchModal.tsx
  src/pages/Main.tsx
  src/routes/Routes.tsx
  src/store/drawer/categoyDrawer.slice.ts
  src/store/store.ts
  src/styles/mainContainer.ts
Labels: feat

#49 ✨ Feat : 상품 등록 링크 입력 시에 해당 상품 미리보기 기능 추가
  src/components/common/UserInput.tsx
  src/components/enrollProd/BodySection.tsx
  src/components/enrollProd/LinkPreview.tsx
  src/hooks/enroll/index.ts
  vite.config.ts
Labels: enhancement

#50 🔧 Settings : Vercel 배포환경에서 프록시 설정
  src/vercel.json
Labels: enhancement

#52 🔧 Settings : rewrite 우선순위 변경
  vercel.json
Labels: enhancement

#55 ✨ Feat : 마이페이지 UI 제작 및 최근 본 상품 조회 기능 구현
  public/images/alarm.png
  public/images/userImage.png
  src/apis/productDetail/getProductDetail.ts
  src/components/common/Footer.tsx
  src/components/enrollProd/AlarmToggle.tsx
  src/components/productDetail/DetailBody.tsx
  src/components/productDetail/EnrollModal.tsx
  src/pages/myPage/MyPage.tsx
  src/routes/Routes.tsx
Labels: enhancement, feat

#54 feat: 검색 detail api 연동, ItemList 컴포넌트 분리
  src/apis/search/axios.ts
  src/components/ItemList/ItemList.tsx
  src/components/mainPage/Category.tsx
  src/components/mainPage/EntireProductList.tsx
  src/components/search/SearchModal.tsx
  src/pages/searchList/SearchDetail.tsx
  src/routes/Routes.tsx
Labels: enhancement, feat

#57 ✨ Feat : pull to refresh 및 페이지 전환 애니메이션 구현
  package-lock.json
  package.json
  src/components/common/PageAnimation.tsx
  src/components/mainPage/products/Item.tsx
  src/layout/Layout.tsx
  src/layout/Refreshing.tsx
  src/pages/enrollProd/EnrollProd.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/product/ProductDetail.tsx
  src/routes/Routes.tsx
  src/styles/mainContainer.ts
Labels: enhancement, feat
